### ISSUE TITLE
Slight documentation error

### ISSUE THREAD

**Issue by nstephenh** [basicer/dicey#2]
The documentation page says min(3d6)=2, when it is 3.

**Comment by nstephenh** [comment]
Also, "representing" is spelled wrong on the documentation page: represneting

**Comment by nstephenh** [comment]
Looks like it was fixed in https://github.com/basicer/dicey/commit/c5eb7a6d565d9e52e50e696069b3210e955c96e4#diff-b1422819d4de1f4c5463ac630f8823402e1642146e70fb0318f14a92bc74eb8a 
and then reverted on a refactor:
https://github.com/basicer/dicey/commit/b7e977b266f3ff86b2616f161a4aef30d324df1e#diff-12e11ec4bc39aae803c4be6a00aaad88fec040cd793abc8e94e3b83307b90259

**Comment by basicer** [comment]
Whoops, if you'd like to make a PR to fix it I'll approve.
